### ISSUE TITLE
Side menu not working

### ISSUE THREAD

**Issue by harialby** [modularcode/modular-admin-html#43] opened 2017-02-27 05:25 UTC
Hi,
I am using modular admin for my mvc project i use the index.html as my layout page .but the side menu not expanding and collapsing.Any suggestions will help me .
Thanks in advance

**Comment by modularcoder** [comment] 2017-02-27 16:13
Duplicate of https://github.com/modularcode/modular-admin-html/issues/44

**Closed by modularcoder** 2017-02-27 16:13 UTC
